### PR TITLE
Five hour fee

### PR DESCRIPTION
**Pull request by celwell**

### CODE REVIEW

**Comment by jborden** [comment]
Ok I will take a look at this and test it. Just off the top of my head, there needs to be changes to dashboard-service for the validation of zones:

https://github.com/Purple-Services/dashboard-service/blob/dev/src/dashboard/zones.clj#L28

**Comment by celwell** [comment]
https://github.com/Purple-Services/dashboard-service/pull/12/files#diff-b57f213c27b05e21cb2130bb50920b3cR53

**Comment by celwell** [comment]
https://github.com/Purple-Services/dashboard-service/pull/12

**Comment by celwell** [comment]
Can we deploy this today?

**Comment by jborden** [comment]
Yes. I assume there is no change to the database because we keep everything as maps in service_fees and service_time_bracket?

**Comment by celwell** [comment]
Correct.

**Comment by celwell** [comment]
You can use this definition of service_fees for testing:

```
{:60 599, :180 399, :300 349}
```

**Comment by jborden** [comment]
The form works, but the zones table is messed up. You need to add an entry for the table header here:
https://github.com/Purple-Services/dashboard-cljs/blob/7f00ba40c20d6e1144e77e4ea5c0bc96b11df168/src/dashboard_cljs/zones.cljs#L370

**Pull request merged**
